---
title: "**Sample STI Data**"
author: "Cornelius Tanui"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    vertical_layout: scroll
    source_code: https://github.com/corneliustanui/Sample_STI_Data.git
    theme: lumen
date: "`r Sys.Date()`"
runtime: shiny
---


```{=html}
<style>
.navbar {
background-color:#438D80;
border-color: #15317E;
}
.navbar-brand {
color: #000000! important;
}
.section.sidebar {
background-color:#438D80;
border-color: #15317E;
color: #000000! important;
}
</style>
```


```{r Clear Evrironment, include = FALSE}
gc()
graphics.off()
rm(list = ls(all.names = TRUE))
```


```{r Function Args, include = FALSE}
link_to_gd <- "https://docs.google.com/spreadsheets/d/1GrcDHTyX_xoCUH_3E-xn6zfxWdSM8PgU/edit?usp=share_link&ouid=109816320875943770961&rtpof=true&sd=true"
folder <- "./Raw Data/"
filename <- "STI Data.xls"

```


```{r Load Data, include = FALSE}

# load raw data
Clean_STI_Data <- 
  readr::read_csv("./Clean Data/Clean STI Data.csv",
                  show_col_types = FALSE)

```


```{r Functions, include = FALSE}

# load functions

source("./Functions/0._load_packages.R")
source("./Functions/1._load_data.R")
source("./Functions/2._prepare_data.R")
source("./Functions/3._server.R")
source("./Functions/4._ui.R")
```


__Page 1__
=====================================  

Sidebar {.sidebar}
-------------------------------------

__These filters affect the both data and charts__

```{r}
ui_setup(data = Clean_STI_Data)[["marital_status"]]
ui_setup(data = Clean_STI_Data)[["occupation"]]
ui_setup(data = Clean_STI_Data)[["church"]]
ui_setup(data = Clean_STI_Data)[["age"]]
ui_setup(data = Clean_STI_Data)[["used_condom"]]

```


Row {.tabset .tabset-fade}
-------------------------------------

### Data
    
```{r Table}

clean_data_reactive <- 
  reactive(
    {
      clean_df <- 
        Clean_STI_Data %>%
        filter(marital_status %in% input$marital_status) %>%
        filter(occupation %in% input$occupation) %>%
        filter(church %in% input$church) %>%
        filter(age >= input$age[1] & age <= input$age[2]) %>%
        filter(used_condom %in% input$used_condom)
      return(clean_df)
      }
    )

DT::renderDataTable(
  {
    DT::datatable(
      clean_data_reactive(),
      filter = "top",
      rownames = FALSE,
      selection = "single",
      extensions = "Buttons",
      options = list(
        pageLength = 15,
        autoWidth = TRUE,
        # dom = "tB",
        dom = "Bfrtip",
        buttons = c("copy", "csv", "excel", "pdf", "print")
        )
      )
   }
 )
   


```

### Average Weight 
    
```{r Chart 1}

plotly::renderPlotly(
  {
    clean_data_reactive() %>% 
      ggplot2::ggplot(
        aes(y = weight,
            x = sex,
            fill = taken_alcohol)) + 
      ggplot2::geom_col(position = "dodge")+
      ggplot2::facet_wrap(~ case_status, scales = "free")+
      ggplot2::labs(
        title = "Distibution of Weight (Kgs) by STI Status and Sex",
        x = "Sex",
        y = "Average Weight",
        fill = "Taken alcohol")+
      ggplot2::theme(
        panel.background =  element_blank(),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "grey"))
    }
  )

```

### Average Height
    
```{r Chart 2}

plotly::renderPlotly(
  {
    clean_data_reactive() %>% 
      ggplot2::ggplot(
        aes(y = height,
            x = sex,
            fill = taken_alcohol)) + 
      ggplot2::geom_col(position = "dodge")+
      ggplot2::facet_wrap(~ case_status, scales = "free")+
      ggplot2::labs(
        title = "Distibution of Height (Kgs) by STI Status and Sex",
        x = "Sex",
        y = "Average Height",
        fill = "Taken alcohol")+
      ggplot2::theme(
        panel.background =  element_blank(),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "grey"))
    }
  )

```
   
__Page 2__
=====================================  

Sidebar {.sidebar}
-------------------------------------

Row {.tabset .tabset-fade}
-------------------------------------

### Chart 1
    
```{r}
```

### Chart 2
    
```{r}
```

### Chart 3
    
```{r}
```